#include "slot_id.h"

int SlotID::MAIN_WINDOW = CRC::ID_INVALID;
int SlotID::MAIN_WINDOW_CONTAINER = CRC::ID_INVALID;

int SlotID::MAIN_SCENE = CRC::ID_INVALID;
int SlotID::MAIN_SCENE_CONTAINER = CRC::ID_INVALID;

int SlotID::USER_INPUT = CRC::ID_INVALID;
int SlotID::USER_INPUT_CONTAINER = CRC::ID_INVALID;